-- CREATE TABLES
-- REFERENCE DATA TABLES ARE LOADED BASED ON USAGE
DROP TABLE IF EXISTS REFDATA_STATUS;
CREATE TABLE REFDATA_STATUS
(
    STATUS_ID          VARCHAR(10) PRIMARY KEY,
    STATUS_DESCRIPTION VARCHAR(45) NOT NULL,
    MAINTAINED_DATE       VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER       VARCHAR(20) DEFAULT 'Platform'
);

DROP TABLE IF EXISTS REFDATA_VENDORS;
CREATE TABLE REFDATA_VENDORS
(
    VENDOR_ID    CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    VENDOR_NAME  VARCHAR(50),
    MAINTAINED_DATE VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID    VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER VARCHAR(20) DEFAULT 'Platform',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS REFDATA_USSTATES;
CREATE TABLE REFDATA_USSTATES
(
    STATE_ID          VARCHAR(2) PRIMARY KEY,
    STATE_DESCRIPTION VARCHAR(65),
    LATTITUDE         VARCHAR(12),
    LONGITUDE         VARCHAR(12),
    MAINTAINED_DATE      VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID         VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER      VARCHAR(20) DEFAULT 'Platform',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS REFDATA_LEGALENTITIES;
CREATE TABLE REFDATA_LEGALENTITIES
(
    LEGALENTITY_GUID CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    LOCATION_NAME    VARCHAR(50),
    ADDRESS          VARCHAR(75),
    CITY             VARCHAR(60),
    STATE_ID         VARCHAR(2),
    ZIPCODE          VARCHAR(12),
    MAINTAINED_USER     VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID        VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_DATE     VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    LOCATION_URL     VARCHAR(99),
    LOCATION_PHONE   VARCHAR(12),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (STATE_ID) REFERENCES REFDATA_USSTATES (STATE_ID)
);

DROP TABLE IF EXISTS REFDATA_ORGANIZATIONS;
CREATE TABLE REFDATA_ORGANIZATIONS
(
    ORGANIZATION_GUID          CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    ORGANIZATION_INTERNAL_CODE VARCHAR(10),
    ORGANIZATION_INTERNAL_ID   VARCHAR(10),
    ORGANIZATION_NAME          VARCHAR(50),
    ADDRESS                    VARCHAR(75),
    CITY                       VARCHAR(60),
    STATE_ID                   VARCHAR(2),
    ZIPCODE                    VARCHAR(12),
    MAINTAINED_USER               VARCHAR(20)  DEFAULT 'Platform',
    STATUS_ID                  VARCHAR(10)  DEFAULT 'Active',
    MAINTAINED_DATE               VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    LEGALENTITY_GUID           CHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (STATE_ID) REFERENCES REFDATA_USSTATES (STATE_ID),
    FOREIGN KEY (LEGALENTITY_GUID) REFERENCES REFDATA_LEGALENTITIES (LEGALENTITY_GUID)
);

DROP TABLE IF EXISTS REFDATA_APPLICATIONS;
CREATE TABLE REFDATA_APPLICATIONS
(
    APP_GUID               CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    APPLICATION_CUSTOMCODE VARCHAR(15),
    APPLICATION_DESC       VARCHAR(50),
    MAINTAINED_USER           VARCHAR(20)  DEFAULT 'Platform',
    MAINTAINED_DATE           VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID              VARCHAR(10)  DEFAULT 'Active',
    VENDOR_ID              CHAR(38),
    INDUSTRY_OID           VARCHAR(49),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (VENDOR_ID) REFERENCES REFDATA_VENDORS (VENDOR_ID)
);

DROP TABLE IF EXISTS REFDATA_SENSITIVITYFLAGS;
CREATE TABLE REFDATA_SENSITIVITYFLAGS
(
    SENSITIVITYFLAG_ID   CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    SENSITIVITYFLAG_DESC VARCHAR(30),
    MAINTAINED_DATE         VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER         VARCHAR(20)  DEFAULT 'Platform',
    STATUS_ID            VARCHAR(10)  DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS REFDATA_CODESETS;
CREATE TABLE REFDATA_CODESETS
(
    CODESETS_ID        CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    CODESET_NAME       VARCHAR(50),
    INDUSTRY_STD       VARCHAR(6),
    STATUS_ID          VARCHAR(10)   DEFAULT 'Active',
    MAINTAINED_DATE       VARCHAR(20)   DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER       VARCHAR(20)   DEFAULT 'Platform',
    FIELD_MAPPING      VARCHAR(40),
    SENSITIVITYFLAG_ID CHAR(38),
    EXTERNALTABLE_ID   VARCHAR(20),
    EXTERNAL_NOTES     VARCHAR(149),
    EXTERNAL_LINK      VARCHAR(99),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (SENSITIVITYFLAG_ID) REFERENCES REFDATA_SENSITIVITYFLAGS (SENSITIVITYFLAG_ID)
);

DROP TABLE IF EXISTS REFDATA_COUNTRIES;
CREATE TABLE REFDATA_COUNTRIES
(
    COUNTRY_CODE             varchar(2) PRIMARY KEY,
    COUNTRY_NAME             varchar(75),
    ALPHA_3                  varchar(3),
    COUNTRY_CODE_ID             integer,
    ISO_3166_2             varchar(25),
    REGION                   VARCHAR(69),
    SUB_REGION               VARCHAR(99),
    INTERMEDIATE_REGION      VARCHAR(99),
    REGION_CODE              VARCHAR(3),
    SUB_REGION_CODE          VARCHAR(3),
    INTERMEDIATE_REGION_CODE VARCHAR(3),
    STATUS_ID          VARCHAR(10)   DEFAULT 'Active',
    MAINTAINED_DATE       VARCHAR(20)   DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER       VARCHAR(20)   DEFAULT 'Platform',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS REFDATA_DATAATTRIBUTES;
CREATE TABLE REFDATA_DATAATTRIBUTES
(
    DATAATTRIBUTE_ID   TEXT PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    DATAATTRIBUTE_NAME VARCHAR(50),
    SENSITIVITYFLAG_ID CHAR(38),
    MAINTAINED_DATE       VARCHAR(20)   DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID          VARCHAR(10)   DEFAULT 'Active',
    MAINTAINED_USER       VARCHAR(20)   DEFAULT 'Platform',
    ATTRIBUTE_TYPE     VARCHAR(10),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (SENSITIVITYFLAG_ID) REFERENCES REFDATA_SENSITIVITYFLAGS (SENSITIVITYFLAG_ID)
);

DROP TABLE IF EXISTS REFDATA_DATASTRUCTURES;
CREATE TABLE REFDATA_DATASTRUCTURES
(
    DATASTRUCTURE_ID   CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    DATASTRUCTURE_NAME VARCHAR(50),
    SENSITIVITYFLAG_ID CHAR(38),
    MAINTAINED_DATE       VARCHAR(20)   DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID          VARCHAR(10)   DEFAULT 'Active',
    MAINTAINED_USER       VARCHAR(20)   DEFAULT 'Platform',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (SENSITIVITYFLAG_ID) REFERENCES REFDATA_SENSITIVITYFLAGS (SENSITIVITYFLAG_ID)
);


DROP TABLE IF EXISTS PLATFORM_DATABUILDING_DATASTRUCTURES_DTL;
DROP TABLE IF EXISTS REFDATA_DATASTRUCTURES_DTL;
CREATE TABLE REFDATA_DATASTRUCTURES_DTL
(
    REFDATA_DATASTRUCTURES_DTL_ID CHAR(38)  PRIMARY KEY  DEFAULT (LOWER(HEX(RANDOMBLOB(16)))) ,
    REFDATA_DATASTRUCTURES_ID     CHAR(38),
    DATAATTRIBUTE_ID                CHAR(38),
    SENSITIVITYFLAG_ID            VARCHAR(5)  DEFAULT 'UNDF',
    MAINTAINED_DATE                    VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    STATUS_ID                       VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER                    VARCHAR(20) DEFAULT 'Platform',
    FOREIGN KEY (REFDATA_DATASTRUCTURES_ID) REFERENCES REFDATA_DATASTRUCTURES (DATASTRUCTURE_ID),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (SENSITIVITYFLAG_ID) REFERENCES REFDATA_SENSITIVITYFLAGS (SENSITIVITYFLAG_ID),
    FOREIGN KEY (DATAATTRIBUTE_ID) REFERENCES REFDATA_DATAATTRIBUTES (DATAATTRIBUTE_ID)
);

DROP TABLE IF EXISTS REFDATA_DEVICETYPES;
CREATE TABLE REFDATA_DEVICETYPES
(
    DEVICETYPE_ID CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    DEVICETYPE    VARCHAR(30),
    MAINTAINED_DATE  VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID     VARCHAR(10)  DEFAULT 'Active',
    MAINTAINED_USER  VARCHAR(20)  DEFAULT 'Platform',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS REFDATA_INDUSTRYSTDS;
CREATE TABLE REFDATA_INDUSTRYSTDS
(
    INDUSTRY_STD     VARCHAR(6) PRIMARY KEY,
    INDUSTRYSTD_DESC VARCHAR(30),
    MAINTAINED_DATE     VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER     VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID        VARCHAR(10) DEFAULT 'Active'
);

DROP TABLE IF EXISTS REFDATA_INDUSTRYSTD_EVENTTYPES;
CREATE TABLE REFDATA_INDUSTRYSTD_EVENTTYPES
(
    EVENTTYPE_ID   VARCHAR(10) NOT NULL,
    EVENTTYPE_DESC VARCHAR(30),
    INDUSTRY_STD   VARCHAR(6),
    MAINTAINED_DATE   VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER   VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID      VARCHAR(10) DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (INDUSTRY_STD) REFERENCES REFDATA_INDUSTRYSTDS (INDUSTRY_STD)
);

DROP TABLE IF EXISTS REFDATA_INDUSTRIES;
CREATE TABLE REFDATA_INDUSTRIES
(
    INDUSTRY_ID   CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    INDUSTRY_NAME VARCHAR(45),
    MAINTAINED_DATE  VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER  VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID     VARCHAR(10) DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS REFDATA_INDUSTRIES_BUSINESS;
CREATE TABLE REFDATA_INDUSTRIES_BUSINESS
(
    INDUSTRYTOBUSINESS_ID CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    INDUSTRY_ID           CHAR(38),
    BUSINESS_AREA         VARCHAR(50),
    MAINTAINED_DATE          VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER          VARCHAR(20)  DEFAULT 'Platform',
    STATUS_ID             VARCHAR(10)  DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (INDUSTRY_ID) REFERENCES REFDATA_INDUSTRIES (INDUSTRY_ID)
);

DROP TABLE IF EXISTS REFDATA_OPERATIONTYPES;
CREATE TABLE REFDATA_OPERATIONTYPES
(
    OPERATIONTYPE_ID   VARCHAR(10) PRIMARY KEY,
    OPERATIONTYPE_NAME VARCHAR(60),
    MAINTAINED_DATE       VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER       VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID          VARCHAR(10) DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS REFDATA_PROFESSIONTYPES;
CREATE TABLE REFDATA_PROFESSIONTYPES
(
    PROFESSIONTYPE_ID   CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    PROFESSIONTYPE_NAME VARCHAR(65),
    MAINTAINED_DATE        VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER        VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID           VARCHAR(10) DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS REFDATA_TERMINOLOGYSTDS;
CREATE TABLE REFDATA_TERMINOLOGYSTDS
(
    TERMINOLOGY_STD        VARCHAR(25) PRIMARY KEY,
    TERMINOLOGYSTD_VERSION VARCHAR(10) NOT NULL,
    TERMINOLOGYSTD_DESC    VARCHAR(129),
    MAINTAINED_DATE           VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER           VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID              VARCHAR(10) DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS REFDATA_TIMEZONES;
CREATE TABLE REFDATA_TIMEZONES
(
    TIMEZONE_ID   VARCHAR(3) PRIMARY KEY,
    TIMEZONE_DESC VARCHAR(25),
    MAINTAINED_DATE  VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER  VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID     VARCHAR(10) DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

-- DATAMODEL
DROP TABLE IF EXISTS DATAMODEL_APIS;
CREATE TABLE DATAMODEL_APIS
(
    API_ID             CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    TECHNOLOGY         VARCHAR(99),
    DATAATTRIBUTE_ID   CHAR(38),
    BASEURLLOCATION    VARCHAR(99),
    APINAME            VARCHAR(99),
    MAINTAINED_DATE       VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER       VARCHAR(20)  DEFAULT 'Platform',
    STATUS_ID          VARCHAR(10)  DEFAULT 'Active',
    PURPOSE            VARCHAR(99),
    DATMODEL_TABLENAME VARCHAR(99),
    APIPARAMS          VARCHAR(149),
    APIEXAMPLE         VARCHAR(199),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS DATAMODEL_DATATABLES;
CREATE TABLE DATAMODEL_DATATABLES
(
    TABLENAME        VARCHAR(129) NOT NULL,
    TABLEINFORMATION VARCHAR(450),
    STATUS_ID        VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_DATE     VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER     VARCHAR(20) DEFAULT 'Platform',
    DATADOMAIN       VARCHAR(49),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS DATAMODEL_DOMAINS;
CREATE TABLE DATAMODEL_DOMAINS
(
    DOMAINNAME        VARCHAR(49) NOT NULL,
    DOMAININFORMATION VARCHAR(149),
    STATUS_ID         VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_DATE      VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER      VARCHAR(20) DEFAULT 'Platform',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS DATAMODEL_QUERIES;
CREATE TABLE IF NOT EXISTS DATAMODEL_QUERIES
(
    DATAMODEL_QUERIES_ID BIGSERIAL,
    DATAMODEL_TABLE      VARCHAR(64),
    DATAMODEL_DOMAIN     VARCHAR(64),
    DATAMODEL_QUERY_TXT  TEXT,
    DATAMODEL_QUERY_DTL  VARCHAR(499),
    MAINTAINED_DATE     TIMESTAMP   DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID           VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER        VARCHAR(20) DEFAULT 'Platform',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

-- DATA TIER
DROP TABLE IF EXISTS DATATIER_CRAWLERS;
CREATE TABLE DATATIER_CRAWLERS
(
    DATACRAWLER_ID      INTEGER PRIMARY KEY AUTOINCREMENT,
    TOKEN               VARCHAR(256),
    CRAWLEDTEXT_DETAILS TEXT,
    MAINTAINED_DATE        VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER        VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID           VARCHAR(10) DEFAULT 'Active',
    REGISTEREDAPP_GUID  CHAR(38),
    ORGANIZATION_GUID   CHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

DROP TABLE IF EXISTS DATATIER_SDP_DATAATTRIBUTES;
CREATE TABLE DATATIER_SDP_DATAATTRIBUTES
(
    DATATIER_SDP_DATAATTRIBUTE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DATAATTRIBUTE_ID   CHAR(38),
    DATAGENTYPE_ID     CHAR(38),
    PARAM_VALUE        VARCHAR(99),
    PARAM_VALUE_METADATA VARCHAR(159),
    MAINTAINED_DATE    TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    STATUS_ID          VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER       VARCHAR(20) DEFAULT 'Platform',
    REGISTEREDAPP_GUID CHAR(38),
    ORGANIZATION_GUID CHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (DATAATTRIBUTE_ID) REFERENCES REFDATA_DATAATTRIBUTES (DATAATTRIBUTE_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

DROP TABLE IF EXISTS DATATIER_SDP_DATASTRUCTURES;
CREATE TABLE DATATIER_SDP_DATASTRUCTURES
(
    DATASTRUCTURE_CORE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DATASTRUCTURE_NAME    VARCHAR(99),
    DATASTRUCTURE_DETAILS TEXT,
    MAINTAINED_DATE          VARCHAR(20)        DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER          VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID             VARCHAR(10) DEFAULT 'Active',
    REGISTEREDAPP_GUID    CHAR(38),
    ORGANIZATION_GUID   CHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

DROP TABLE IF EXISTS DATATIER_TOKENS;
CREATE TABLE DATATIER_TOKENS
(
    DATATOKEN_ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    TOKEN              VARCHAR(128),
    MAINTAINED_DATE       VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID          VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER       VARCHAR(20) DEFAULT 'Platform',
    REGISTEREDAPP_GUID CHAR(38),
    ORGANIZATION_GUID  CHAR(38),
    INTFC_TYPE         VARCHAR(10) DEFAULT 'API',
    DATASOURCE_ID      CHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID),
    FOREIGN KEY (DATASOURCE_ID) REFERENCES PLATFORM_DATASOURCES (PLATFORM_DATASOURCES_ID)
);

-- PLATFORM
DROP TABLE IF EXISTS PLATFORM_CODESETS;
CREATE TABLE PLATFORM_CODESETS
(
    PLATFORM_CODESET_ID CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    APPLICATION_GUID    CHAR(38),
    ORGANIZATION_GUID   CHAR(38),
    CODESETS_ID         CHAR(38),
    MAINTAINED_DATE        VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID           VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER        VARCHAR(20) DEFAULT 'Platform',
    ORIGINALCODE_VALUE  VARCHAR(40),
    ORIGINALCODE_DESC   VARCHAR(149),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (APPLICATION_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

DROP TABLE IF EXISTS PLATFORM_CODESETS_INDUSTRYSTDS;
CREATE TABLE PLATFORM_CODESETS_INDUSTRYSTDS
(
    TERMCODESET_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CUI            VARCHAR(8) NULL,
    LAT            VARCHAR(3) NULL,
    TS             VARCHAR(1) NULL,
    LUI            VARCHAR(10) NULL,
    STT            VARCHAR(3) NULL,
    SUI            VARCHAR(10) NULL,
    ISPREF         VARCHAR(1) NULL,
    AUI            VARCHAR(9) NULL,
    SAUI           VARCHAR(50) NULL,
    SCUI           VARCHAR(50) NULL,
    SDUI           VARCHAR(50) NULL,
    SAB            VARCHAR(25) NULL,
    TTY            VARCHAR(20) NULL,
    CODE           VARCHAR(50) NULL,
    STR            TEXT NULL,
    SRL            INT NULL,
    SUPPRESS       VARCHAR(1) NULL,
    CVF            INT NULL,
    MAINTAINED_DATE  VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE  VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    MAINTAINED_USER  VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID        VARCHAR(10) DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (SAB) REFERENCES REFDATA_INDUSTRYSTDS (INDUSTRY_STD)
);

DROP TABLE IF EXISTS PLATFORM_CODESETS_XMAPS;
CREATE TABLE PLATFORM_CODESETS_XMAPS
(
    CODESETCROSSMAP_ID  CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    REGISTEREDAPP_GUID  CHAR(38),
    ORGANIZATION_GUID   CHAR(38),
    TERMINOLOGYSTD_FROM VARCHAR(25),
    TERMINOLOGYSTD_TO   VARCHAR(25),
    MAINTAINED_DATE        VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID           VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER        VARCHAR(20) DEFAULT 'Platform',
    TRANSFORMCODE_VALUE VARCHAR(40),
    TRANSFORMCODE_DESC  VARCHAR(129),
    ORIGINALCODE_VALUE  VARCHAR(40),
    ORIGINALCODE_DESC   VARCHAR(129),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID),
    FOREIGN KEY (TERMINOLOGYSTD_FROM) REFERENCES REFDATA_TERMINOLOGYSTDS (TERMINOLOGY_STD),
    FOREIGN KEY (TERMINOLOGYSTD_TO) REFERENCES REFDATA_TERMINOLOGYSTDS (TERMINOLOGY_STD)
);

DROP TABLE IF EXISTS PLATFORM_DATASOURCES;
CREATE TABLE PLATFORM_DATASOURCES
(
    PLATFORM_DATASOURCES_ID CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    DATASOURCE_NAME         VARCHAR(79),
    DATASOURCE_TYPE         VARCHAR(30),
    DATASOURCE_TECHNOLOGY   VARCHAR(40),
    HOST_NAME               VARCHAR(99),
    HOST_PORT               INT,
    HOST_UID                VARCHAR(79),
    HOST_ADDTNLDTLS          VARCHAR(149),
    CUSTOM_URL         VARCHAR(129),
    APP_TOKEN          VARCHAR(256),
    CUSTOM_TOKEN       VARCHAR(256),
    BEARER_TOKEN       VARCHAR(256),
    MAINTAINED_DATE            VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    STATUS_ID               VARCHAR(10)  DEFAULT 'Active',
    MAINTAINED_USER            VARCHAR(20)  DEFAULT 'Platform',
    ORGANIZATION_GUID       CHAR(38),
    REGISTEREDAPP_GUID      CHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

DROP TABLE IF EXISTS PLATFORM_DATAGENERATION_DATAATTRIBUTES;
CREATE TABLE PLATFORM_DATAGENERATION_DATAATTRIBUTES
(
    DATAGENTYPE_ID          CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    DATAGENTYPE_DESCRIPTION VARCHAR(65),
    DEFINITION              VARCHAR(255),
    DEFINITION_METADATA  VARCHAR(75),
    DATAATTRIBUTE_ID        CHAR(38),
    MAINTAINED_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    STATUS_ID               VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER            VARCHAR(20) DEFAULT 'Platform',
    QUANTITY                INTEGER,
    MAXRECORDS_IN_SOURCE    INTEGER,
    REGISTEREDAPP_GUID      CHAR(38),
    ORGANIZATION_GUID       CHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID),
    FOREIGN KEY (DATAATTRIBUTE_ID) REFERENCES REFDATA_DATAATTRIBUTES (DATAATTRIBUTE_ID)
);

DROP TABLE IF EXISTS PLATFORM_DATABUILDING_DATAATTRIBUTES;
CREATE TABLE PLATFORM_DATABUILDING_DATAATTRIBUTES
(
    DATABUILD_DATAATTRIBUTE_ID CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    DATABUILD_DESCRIPTION      VARCHAR(65),
    DEFINITION                 VARCHAR(255),
    MAINTAINED_DATE               VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    STATUS_ID                  VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER               VARCHAR(20) DEFAULT 'Platform',
    QUANTITY                   INTEGER,
    MAXRECORDS_IN_SOURCE       INTEGER,
    REGISTEREDAPP_GUID         CHAR(38),
    ORGANIZATION_GUID          CHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

DROP TABLE IF EXISTS PLATFORM_DATABUILDING_DATAATTRIBUTES_DTL;
CREATE TABLE PLATFORM_DATABUILDING_DATAATTRIBUTES_DTL
(
    DATABUILD_DATAATTRIBUTE_DTL_ID CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    DATABUILD_DATAATTRIBUTE_ID     CHAR(38),
    DATAATTRIBUTE_ID               CHAR(38),
    MAINTAINED_DATE                VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    PARAM_NAME                     VARCHAR(30),
    PARAM_OPERATOR                 VARCHAR(7),
    PARAM_VALUE                    VARCHAR(65),
    STATUS_ID                      VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER                   VARCHAR(20) DEFAULT 'Platform',
    FOREIGN KEY (DATABUILD_DATAATTRIBUTE_ID) REFERENCES PLATFORM_DATABUILDING_DATAATTRIBUTES (DATABUILD_DATAATTRIBUTE_ID),
    FOREIGN KEY (PARAM_OPERATOR) REFERENCES REFDATA_OPERATIONTYPES (OPERATIONTYPE_ID),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (DATAATTRIBUTE_ID) REFERENCES REFDATA_DATAATTRIBUTES (DATAATTRIBUTE_ID)
);

DROP TABLE IF EXISTS PLATFORM_DATABUILDING_DATASTRUCTURES;
CREATE TABLE PLATFORM_DATABUILDING_DATASTRUCTURES
(
    DATABUILD_DATASTRUCTURES_ID CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    DATABUILD_DESCRIPTION       VARCHAR(65),
    DEFINITION                  VARCHAR(255),
    DATASTRUCTURE_ID            CHAR(38),
    MAINTAINED_DATE                VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    STATUS_ID                   VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER                VARCHAR(20) DEFAULT 'Platform',
    QUANTITY                    INTEGER,
    MAXRECORDS_IN_SOURCE        INTEGER,
    REGISTEREDAPP_GUID          CHAR(38),
    ORGANIZATION_GUID           CHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (DATASTRUCTURE_ID) REFERENCES REFDATA_DATASTRUCTURES (DATASTRUCTURE_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

DROP TABLE IF EXISTS REFDATA_RULESETS;
DROP TABLE IF EXISTS PLATFORM_RULESETS;
CREATE TABLE PLATFORM_RULESETS
(
    RULE_ID         CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    RULE_NAME       VARCHAR(65),
    MAINTAINED_DATE    VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    MAINTAINED_USER    VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID       VARCHAR(10) DEFAULT 'Active',
    REGISTEREDAPP_GUID            CHAR(38),
    ORGANIZATION_GUID             CHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

DROP TABLE IF EXISTS PLATFORM_RULESETS_DEFINITIONS;
DROP TABLE IF EXISTS PLATFORM_RULESETS_DTL;
CREATE TABLE PLATFORM_RULESETS_DTL
(
    RULESET_DEFINITIONS_ID   CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    RULESET_DEFINITIONS_NAME VARCHAR(65),
    RULESET_ID               CHAR(38),
    STEPORDER_ID             INTEGER,
    OPERATIONTYPE_ID         VARCHAR(10),
    RULESET_DEFVALUE         VARCHAR(20),
    STATUS_ID                VARCHAR(10)  DEFAULT 'Active',
    MAINTAINED_DATE             VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE          VARCHAR(20)  DEFAULT (DATETIME('NOW', '+1 years')),
    MAINTAINED_USER             VARCHAR(20)  DEFAULT 'Platform',
    TERM_DATE                VARCHAR(20),
    DATAATTRIBUTE_ID         CHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (DATAATTRIBUTE_ID) REFERENCES REFDATA_DATAATTRIBUTES (DATAATTRIBUTE_ID),
    FOREIGN KEY (OPERATIONTYPE_ID) REFERENCES REFDATA_OPERATIONTYPES (OPERATIONTYPE_ID),
    FOREIGN KEY (RULESET_ID) REFERENCES PLATFORM_RULESETS (RULE_ID)
);

DROP TABLE IF EXISTS PLATFORM_TOKENS_XMAPS;
CREATE TABLE PLATFORM_TOKENS_XMAPS
(
    PLATFORM_TOKENS_XMAP_ID CHAR(38) PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
    DATASTRUCTURE_ID        CHAR(38),
    XMAP_DETAILS            VARCHAR(75),
    DATAATTRIBUTE_ID        CHAR(38),
    FIELDORDER_ID           INTEGER DEFAULT 1,
    MAINTAINED_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE         VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    STATUS_ID               VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER            VARCHAR(20) DEFAULT 'Platform',
    REGISTEREDAPP_GUID      CHAR(38),
    ORGANIZATION_GUID       CHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (DATAATTRIBUTE_ID) REFERENCES REFDATA_DATAATTRIBUTES (DATAATTRIBUTE_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

-- INDEXES
DROP INDEX IF EXISTS DATATIER_SDP_DATAATTRIBUTES_UINDEX
CREATE INDEX DATATIER_SDP_DATAATTRIBUTES_UINDEX
    ON DATATIER_SDP_DATAATTRIBUTES (DATATIER_SDP_DATAATTRIBUTE_ID, PARAM_VALUE,PARAM_VALUE_METADATA, MAINTAINED_DATE,
                                    DATAATTRIBUTE_ID, STATUS_ID, MAINTAINED_USER, REGISTEREDAPP_GUID);

DROP INDEX IF EXISTS DATATIER_CRAWLER_INDX;
CREATE INDEX DATATIER_CRAWLER_INDX ON DATATIER_CRAWLERS
    ( DATACRAWLER_ID ASC, TOKEN ASC, MAINTAINED_DATE ASC, STATUS_ID ASC, REGISTEREDAPP_GUID ASC, ORGANIZATION_GUID ASC )

DROP INDEX IF EXISTS DATATIER_SDP_DATASTRUCTURES_INDX;
CREATE INDEX DATATIER_SDP_DATASTRUCTURES_INDEX ON DATATIER_SDP_DATASTRUCTURES
    ( DATASTRUCTURE_CORE_ID ASC, DATASTRUCTURE_NAME ASC, MAINTAINED_DATE ASC, STATUS_ID ASC, REGISTEREDAPP_GUID ASC );

DROP INDEX IF EXISTS DATATIER_TOKENS_INDX;
CREATE INDEX DATATIER_TOKENS_INDEX ON DATATIER_TOKENS
    ( DATATOKEN_ID ASC, TOKEN ASC, MAINTAINED_DATE ASC,
     STATUS_ID ASC, REGISTEREDAPP_GUID ASC, ORGANIZATION_GUID ASC,
     INTFC_TYPE ASC, DATASOURCE_ID ASC);

DROP INDEX IF EXISTS PLATFORM_CODESETS_INDUSTRYSTDS_INDX;
CREATE INDEX PLATFORM_CODESETS_INDUSTRYSTDS_INDX ON PLATFORM_CODESETS_INDUSTRYSTDS
    ( TERMCODESET_ID ASC, MAINTAINED_DATE ASC, STATUS_ID ASC, CUI ASC,
     LAT ASC, TS ASC, LUI ASC, STT ASC, SUI ASC, ISPREF ASC, AUI ASC,
     SAUI ASC, SCUI ASC, SDUI ASC, SAB ASC, TTY ASC, CODE ASC, STR ASC,
     SRL ASC, SUPPRESS ASC, CVF ASC);