-- CREATE TABLES
-- REFERENCE DATA TABLES ARE LOADED BASED ON USAGE
DROP TABLE IF EXISTS REFDATA_STATUS;
CREATE TABLE REFDATA_STATUS
(
    STATUS_ID          VARCHAR(10) PRIMARY KEY,
    STATUS_DESCRIPTION VARCHAR(45) NOT NULL,
    MAINTAINED_DATE       VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER       VARCHAR(20) DEFAULT 'Platform'
);

DROP TABLE IF EXISTS REFDATA_VENDORS;
CREATE TABLE REFDATA_VENDORS
(
    VENDOR_ID    VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    VENDOR_NAME  VARCHAR(50),
    MAINTAINED_DATE VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID    VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER VARCHAR(20) DEFAULT 'Platform',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

CREATE TRIGGER REFDATA_VENDORS_UUID_FORMATTER
AFTER INSERT ON REFDATA_VENDORS
BEGIN
    UPDATE REFDATA_VENDORS SET VENDOR_ID = concat(substr(VENDOR_ID,0,9)||'-'
    || substr(VENDOR_ID,9,4)||'-'|| substr(VENDOR_ID,13,4)||'-'
    || substr(VENDOR_ID,17,4)||'-'|| substr(VENDOR_ID,21,12))
    WHERE VENDOR_ID NOT LIKE '%-%';
END;

DROP TABLE IF EXISTS REFDATA_USSTATES;
CREATE TABLE REFDATA_USSTATES
(
    STATE_ID          VARCHAR(2) PRIMARY KEY,
    STATE_DESCRIPTION VARCHAR(65),
    LATTITUDE         VARCHAR(12),
    LONGITUDE         VARCHAR(12),
    MAINTAINED_DATE      VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID         VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER      VARCHAR(20) DEFAULT 'Platform',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS REFDATA_LEGALENTITIES;
CREATE TABLE REFDATA_LEGALENTITIES
(
    LEGALENTITY_GUID VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    LOCATION_NAME    VARCHAR(50),
    ADDRESS          VARCHAR(75),
    CITY             VARCHAR(60),
    STATE_ID         VARCHAR(2),
    ZIPCODE          VARCHAR(12),
    MAINTAINED_USER     VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID        VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_DATE     VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    LOCATION_URL     VARCHAR(99),
    LOCATION_PHONE   VARCHAR(12),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (STATE_ID) REFERENCES REFDATA_USSTATES (STATE_ID)
);

CREATE TRIGGER REFDATA_LEGALENTITIES_UUID_FORMATTER
AFTER INSERT ON REFDATA_LEGALENTITIES
BEGIN
    UPDATE REFDATA_LEGALENTITIES SET LEGALENTITY_GUID = concat(substr(LEGALENTITY_GUID,0,9)||'-'
    || substr(LEGALENTITY_GUID,9,4)||'-'|| substr(LEGALENTITY_GUID,13,4)||'-'
    || substr(LEGALENTITY_GUID,17,4)||'-'|| substr(LEGALENTITY_GUID,21,12))
    WHERE LEGALENTITY_GUID NOT LIKE '%-%';
END;

DROP TABLE IF EXISTS REFDATA_ORGANIZATIONS;
CREATE TABLE REFDATA_ORGANIZATIONS
(
    ORGANIZATION_GUID          VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    ORGANIZATION_INTERNAL_CODE VARCHAR(10),
    ORGANIZATION_INTERNAL_ID   VARCHAR(10),
    ORGANIZATION_NAME          VARCHAR(50),
    ADDRESS                    VARCHAR(75),
    CITY                       VARCHAR(60),
    STATE_ID                   VARCHAR(2),
    ZIPCODE                    VARCHAR(12),
    MAINTAINED_USER               VARCHAR(20)  DEFAULT 'Platform',
    STATUS_ID                  VARCHAR(10)  DEFAULT 'Active',
    MAINTAINED_DATE               VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    LEGALENTITY_GUID           VARCHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (STATE_ID) REFERENCES REFDATA_USSTATES (STATE_ID),
    FOREIGN KEY (LEGALENTITY_GUID) REFERENCES REFDATA_LEGALENTITIES (LEGALENTITY_GUID)
);

CREATE TRIGGER REFDATA_ORGANIZATIONS_UUID_FORMATTER
AFTER INSERT ON REFDATA_ORGANIZATIONS
BEGIN
    UPDATE REFDATA_ORGANIZATIONS SET ORGANIZATION_GUID = concat(substr(ORGANIZATION_GUID,0,9)||'-'
    || substr(ORGANIZATION_GUID,9,4)||'-'|| substr(ORGANIZATION_GUID,13,4)||'-'
    || substr(ORGANIZATION_GUID,17,4)||'-'|| substr(ORGANIZATION_GUID,21,12))
    WHERE ORGANIZATION_GUID NOT LIKE '%-%';
END;

DROP TABLE IF EXISTS REFDATA_APPLICATIONS;
CREATE TABLE REFDATA_APPLICATIONS
(
    APP_GUID               VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    APPLICATION_CUSTOMCODE VARCHAR(15),
    APPLICATION_DESC       VARCHAR(50),
    MAINTAINED_USER           VARCHAR(20)  DEFAULT 'Platform',
    MAINTAINED_DATE           VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID              VARCHAR(10)  DEFAULT 'Active',
    VENDOR_ID              VARCHAR(38),
    INDUSTRY_OID           VARCHAR(49),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (VENDOR_ID) REFERENCES REFDATA_VENDORS (VENDOR_ID)
);

CREATE TRIGGER REFDATA_APPLICATIONS_UUID_FORMATTER
AFTER INSERT ON REFDATA_APPLICATIONS
BEGIN
    UPDATE REFDATA_APPLICATIONS SET APP_GUID = concat(substr(APP_GUID,0,9)||'-'
    || substr(APP_GUID,9,4)||'-'|| substr(APP_GUID,13,4)||'-'
    || substr(APP_GUID,17,4)||'-'|| substr(APP_GUID,21,12))
    WHERE APP_GUID NOT LIKE '%-%';
END;

DROP TABLE IF EXISTS REFDATA_SENSITIVITYFLAGS;
CREATE TABLE REFDATA_SENSITIVITYFLAGS
(
    SENSITIVITYFLAG_ID   VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    SENSITIVITYFLAG_DESC VARCHAR(30),
    MAINTAINED_DATE         VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER         VARCHAR(20)  DEFAULT 'Platform',
    STATUS_ID            VARCHAR(10)  DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

CREATE TRIGGER REFDATA_SENSITIVITYFLAGS_UUID_FORMATTER
AFTER INSERT ON REFDATA_SENSITIVITYFLAGS
BEGIN
    UPDATE REFDATA_SENSITIVITYFLAGS SET SENSITIVITYFLAG_ID = concat(substr(SENSITIVITYFLAG_ID,0,9)||'-'
    || substr(SENSITIVITYFLAG_ID,9,4)||'-'|| substr(SENSITIVITYFLAG_ID,13,4)||'-'
    || substr(SENSITIVITYFLAG_ID,17,4)||'-'|| substr(SENSITIVITYFLAG_ID,21,12))
    WHERE SENSITIVITYFLAG_ID NOT LIKE '%-%';
END;

DROP TABLE IF EXISTS REFDATA_CODESETS;
CREATE TABLE REFDATA_CODESETS
(
    CODESETS_ID        VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    CODESET_NAME       VARCHAR(50),
    INDUSTRY_STD       VARCHAR(6),
    STATUS_ID          VARCHAR(10)   DEFAULT 'Active',
    MAINTAINED_DATE       VARCHAR(20)   DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER       VARCHAR(20)   DEFAULT 'Platform',
    FIELD_MAPPING      VARCHAR(40),
    SENSITIVITYFLAG_ID VARCHAR(38),
    EXTERNALTABLE_ID   VARCHAR(20),
    EXTERNAL_NOTES     VARCHAR(149),
    EXTERNAL_LINK      VARCHAR(99),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (SENSITIVITYFLAG_ID) REFERENCES REFDATA_SENSITIVITYFLAGS (SENSITIVITYFLAG_ID)
);

CREATE TRIGGER REFDATA_CODESETS_UUID_FORMATTER
AFTER INSERT ON REFDATA_CODESETS
BEGIN
    UPDATE REFDATA_CODESETS SET CODESETS_ID = concat(substr(CODESETS_ID,0,9)||'-'
    || substr(CODESETS_ID,9,4)||'-'|| substr(CODESETS_ID,13,4)||'-'
    || substr(CODESETS_ID,17,4)||'-'|| substr(CODESETS_ID,21,12))
    WHERE CODESETS_ID NOT LIKE '%-%';
END;

DROP TABLE IF EXISTS REFDATA_COUNTRIES;
CREATE TABLE REFDATA_COUNTRIES
(
    COUNTRY_CODE             varchar(2) PRIMARY KEY,
    COUNTRY_NAME             varchar(75),
    ALPHA_3                  varchar(3),
    COUNTRY_CODE_ID             integer,
    ISO_3166_2             varchar(25),
    REGION                   VARCHAR(69),
    SUB_REGION               VARCHAR(99),
    INTERMEDIATE_REGION      VARCHAR(99),
    REGION_CODE              VARCHAR(3),
    SUB_REGION_CODE          VARCHAR(3),
    INTERMEDIATE_REGION_CODE VARCHAR(3),
    STATUS_ID          VARCHAR(10)   DEFAULT 'Active',
    MAINTAINED_DATE       VARCHAR(20)   DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER       VARCHAR(20)   DEFAULT 'Platform',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS REFDATA_DATAATTRIBUTES;
CREATE TABLE REFDATA_DATAATTRIBUTES
(
    DATAATTRIBUTE_ID   VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    DATAATTRIBUTE_NAME VARCHAR(50),
    SENSITIVITYFLAG_ID VARCHAR(38),
    MAINTAINED_DATE       VARCHAR(20)   DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID          VARCHAR(10)   DEFAULT 'Active',
    MAINTAINED_USER       VARCHAR(20)   DEFAULT 'Platform',
    ATTRIBUTE_TYPE     VARCHAR(10),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (SENSITIVITYFLAG_ID) REFERENCES REFDATA_SENSITIVITYFLAGS (SENSITIVITYFLAG_ID)
);

CREATE TRIGGER RREFDATA_DATAATTRIBUTES_UUID_FORMATTER
AFTER INSERT ON REFDATA_DATAATTRIBUTES
BEGIN
    UPDATE REFDATA_DATAATTRIBUTES SET DATAATTRIBUTE_ID = concat(substr(DATAATTRIBUTE_ID,0,9)||'-'
    || substr(DATAATTRIBUTE_ID,9,4)||'-'|| substr(DATAATTRIBUTE_ID,13,4)||'-'
    || substr(DATAATTRIBUTE_ID,17,4)||'-'|| substr(DATAATTRIBUTE_ID,21,12))
    WHERE DATAATTRIBUTE_ID NOT LIKE '%-%';
END;

DROP TABLE IF EXISTS REFDATA_DATASTRUCTURES;
CREATE TABLE REFDATA_DATASTRUCTURES
(
    DATASTRUCTURE_ID   VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    DATASTRUCTURE_NAME VARCHAR(50),
    SENSITIVITYFLAG_ID VARCHAR(38),
    MAINTAINED_DATE       VARCHAR(20)   DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID          VARCHAR(10)   DEFAULT 'Active',
    MAINTAINED_USER       VARCHAR(20)   DEFAULT 'Platform',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (SENSITIVITYFLAG_ID) REFERENCES REFDATA_SENSITIVITYFLAGS (SENSITIVITYFLAG_ID)
);

CREATE TRIGGER REFDATA_DATASTRUCTURES_UUID_FORMATTER
AFTER INSERT ON REFDATA_DATASTRUCTURES
BEGIN
    UPDATE REFDATA_DATASTRUCTURES SET DATASTRUCTURE_ID= concat(substr(DATASTRUCTURE_ID,0,9)||'-'
    || substr(DATASTRUCTURE_ID,9,4)||'-'|| substr(DATASTRUCTURE_ID,13,4)||'-'
    || substr(DATASTRUCTURE_ID,17,4)||'-'|| substr(DATASTRUCTURE_ID,21,12))
    WHERE DATASTRUCTURE_ID NOT LIKE '%-%';
END;


DROP TABLE IF EXISTS PLATFORM_DATABUILDING_DATASTRUCTURES_DTL;
DROP TABLE IF EXISTS REFDATA_DATASTRUCTURES_DTL;
CREATE TABLE REFDATA_DATASTRUCTURES_DTL
(
    REFDATA_DATASTRUCTURES_DTL_ID VARCHAR(38)  PRIMARY KEY  DEFAULT (UPPER(HEX(RANDOMBLOB(16)))) ,
    REFDATA_DATASTRUCTURES_ID     VARCHAR(38),
    DATAATTRIBUTE_ID                VARCHAR(38),
    SENSITIVITYFLAG_ID            VARCHAR(5)  DEFAULT 'UNDF',
    MAINTAINED_DATE                    VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    STATUS_ID                       VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER                    VARCHAR(20) DEFAULT 'Platform',
    FOREIGN KEY (REFDATA_DATASTRUCTURES_ID) REFERENCES REFDATA_DATASTRUCTURES (DATASTRUCTURE_ID),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (SENSITIVITYFLAG_ID) REFERENCES REFDATA_SENSITIVITYFLAGS (SENSITIVITYFLAG_ID),
    FOREIGN KEY (DATAATTRIBUTE_ID) REFERENCES REFDATA_DATAATTRIBUTES (DATAATTRIBUTE_ID)
);

CREATE TRIGGER REFDATA_DATASTRUCTURES_DTL_UUID_FORMATTER
AFTER INSERT ON REFDATA_DATASTRUCTURES_DTL
BEGIN
    UPDATE REFDATA_DATASTRUCTURES_DTL SET REFDATA_DATASTRUCTURES_DTL_ID= concat(substr(REFDATA_DATASTRUCTURES_DTL_ID,0,9)||'-'
    || substr(REFDATA_DATASTRUCTURES_DTL_ID,9,4)||'-'|| substr(REFDATA_DATASTRUCTURES_DTL_ID,13,4)||'-'
    || substr(REFDATA_DATASTRUCTURES_DTL_ID,17,4)||'-'|| substr(REFDATA_DATASTRUCTURES_DTL_ID,21,12))
    WHERE REFDATA_DATASTRUCTURES_DTL_ID NOT LIKE '%-%';
END;

DROP TABLE IF EXISTS REFDATA_DEVICETYPES;
CREATE TABLE REFDATA_DEVICETYPES
(
    DEVICETYPE_ID VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    DEVICETYPE    VARCHAR(30),
    MAINTAINED_DATE  VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID     VARCHAR(10)  DEFAULT 'Active',
    MAINTAINED_USER  VARCHAR(20)  DEFAULT 'Platform',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

CREATE TRIGGER REFDATA_DEVICETYPES_UUID_FORMATTER
AFTER INSERT ON REFDATA_DEVICETYPES
BEGIN
    UPDATE REFDATA_DEVICETYPES SET DEVICETYPE_ID = concat(substr(DEVICETYPE_ID,0,9)||'-'
    || substr(DEVICETYPE_ID,9,4)||'-'|| substr(DEVICETYPE_ID,13,4)||'-'
    || substr(DEVICETYPE_ID,17,4)||'-'|| substr(DEVICETYPE_ID,21,12))
    WHERE DEVICETYPE_ID NOT LIKE '%-%';;
END;

DROP TABLE IF EXISTS REFDATA_INDUSTRYSTDS;
CREATE TABLE REFDATA_INDUSTRYSTDS
(
    INDUSTRY_STD     VARCHAR(6) PRIMARY KEY,
    INDUSTRYSTD_DESC VARCHAR(30),
    MAINTAINED_DATE     VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER     VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID        VARCHAR(10) DEFAULT 'Active'
);

DROP TABLE IF EXISTS REFDATA_INDUSTRYSTD_EVENTTYPES;
CREATE TABLE REFDATA_INDUSTRYSTD_EVENTTYPES
(
    EVENTTYPE_ID   VARCHAR(10) NOT NULL,
    EVENTTYPE_DESC VARCHAR(30),
    INDUSTRY_STD   VARCHAR(6),
    MAINTAINED_DATE   VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER   VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID      VARCHAR(10) DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (INDUSTRY_STD) REFERENCES REFDATA_INDUSTRYSTDS (INDUSTRY_STD)
);

DROP TABLE IF EXISTS REFDATA_INDUSTRIES;
CREATE TABLE REFDATA_INDUSTRIES
(
    INDUSTRY_ID   VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    INDUSTRY_NAME VARCHAR(45),
    MAINTAINED_DATE  VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER  VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID     VARCHAR(10) DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

CREATE TRIGGER REFDATA_INDUSTRIES_UUID_FORMATTER
AFTER INSERT ON REFDATA_INDUSTRIES
BEGIN
    UPDATE REFDATA_INDUSTRIES SET INDUSTRY_ID = concat(substr(INDUSTRY_ID,0,9)||'-'
    || substr(INDUSTRY_ID,9,4)||'-'|| substr(INDUSTRY_ID,13,4)||'-'
    || substr(INDUSTRY_ID,17,4)||'-'|| substr(INDUSTRY_ID,21,12))
    WHERE INDUSTRY_ID NOT LIKE '%-%';;
END;

DROP TABLE IF EXISTS REFDATA_INDUSTRIES_BUSINESS;
CREATE TABLE REFDATA_INDUSTRIES_BUSINESS
(
    INDUSTRYTOBUSINESS_ID VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    INDUSTRY_ID           VARCHAR(38),
    BUSINESS_AREA         VARCHAR(50),
    MAINTAINED_DATE          VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER          VARCHAR(20)  DEFAULT 'Platform',
    STATUS_ID             VARCHAR(10)  DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (INDUSTRY_ID) REFERENCES REFDATA_INDUSTRIES (INDUSTRY_ID)
);

CREATE TRIGGER REFDATA_INDUSTRIES_BUSINESS_UUID_FORMATTER
AFTER INSERT ON REFDATA_INDUSTRIES_BUSINESS
BEGIN
    UPDATE REFDATA_INDUSTRIES_BUSINESS SET INDUSTRYTOBUSINESS_ID = concat(substr(INDUSTRYTOBUSINESS_ID,0,9)||'-'
    || substr(INDUSTRYTOBUSINESS_ID,9,4)||'-'|| substr(INDUSTRYTOBUSINESS_ID,13,4)||'-'
    || substr(INDUSTRYTOBUSINESS_ID,17,4)||'-'|| substr(INDUSTRYTOBUSINESS_ID,21,12))
    WHERE INDUSTRYTOBUSINESS_ID NOT LIKE '%-%';;
END;

DROP TABLE IF EXISTS REFDATA_OPERATIONTYPES;
CREATE TABLE REFDATA_OPERATIONTYPES
(
    OPERATIONTYPE_ID   VARCHAR(10) PRIMARY KEY,
    OPERATIONTYPE_NAME VARCHAR(60),
    MAINTAINED_DATE       VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER       VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID          VARCHAR(10) DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS REFDATA_PROFESSIONTYPES;
CREATE TABLE REFDATA_PROFESSIONTYPES
(
    PROFESSIONTYPE_ID   VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    PROFESSIONTYPE_NAME VARCHAR(65),
    MAINTAINED_DATE        VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER        VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID           VARCHAR(10) DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

CREATE TRIGGER REFDATA_PROFESSIONTYPES_UUID_FORMATTER
AFTER INSERT ON REFDATA_PROFESSIONTYPES
BEGIN
    UPDATE REFDATA_PROFESSIONTYPES SET PROFESSIONTYPE_ID = concat(substr(PROFESSIONTYPE_ID,0,9)||'-'
    || substr(PROFESSIONTYPE_ID,9,4)||'-'|| substr(PROFESSIONTYPE_ID,13,4)||'-'
    || substr(PROFESSIONTYPE_ID,17,4)||'-'|| substr(PROFESSIONTYPE_ID,21,12))
    WHERE PROFESSIONTYPE_ID NOT LIKE '%-%';;
END;

DROP TABLE IF EXISTS REFDATA_TERMINOLOGYSTDS;
CREATE TABLE REFDATA_TERMINOLOGYSTDS
(
    TERMINOLOGY_STD        VARCHAR(25) PRIMARY KEY,
    TERMINOLOGYSTD_VERSION VARCHAR(10) NOT NULL,
    TERMINOLOGYSTD_DESC    VARCHAR(129),
    MAINTAINED_DATE           VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER           VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID              VARCHAR(10) DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS REFDATA_TIMEZONES;
CREATE TABLE REFDATA_TIMEZONES
(
    TIMEZONE_ID   VARCHAR(3) PRIMARY KEY,
    TIMEZONE_DESC VARCHAR(25),
    MAINTAINED_DATE  VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER  VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID     VARCHAR(10) DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

-- DATAMODEL
DROP TABLE IF EXISTS DATAMODEL_APIS;
CREATE TABLE DATAMODEL_APIS
(
    API_ID             VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    TECHNOLOGY         VARCHAR(99),
    DATAATTRIBUTE_ID   VARCHAR(38),
    BASEURLLOCATION    VARCHAR(99),
    APINAME            VARCHAR(99),
    MAINTAINED_DATE       VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER       VARCHAR(20)  DEFAULT 'Platform',
    STATUS_ID          VARCHAR(10)  DEFAULT 'Active',
    PURPOSE            VARCHAR(99),
    DATMODEL_TABLENAME VARCHAR(99),
    APIPARAMS          VARCHAR(149),
    APIEXAMPLE         VARCHAR(199),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

CREATE TRIGGER DATAMODEL_APIS_UUID_FORMATTER
AFTER INSERT ON DATAMODEL_APIS
BEGIN
    UPDATE DATAMODEL_APIS SET API_ID = concat(substr(API_ID,0,9)||'-'
    || substr(API_ID,9,4)||'-'|| substr(API_ID,13,4)||'-'
    || substr(API_ID,17,4)||'-'|| substr(API_ID,21,12))
    WHERE API_ID NOT LIKE '%-%';;
END;

DROP TABLE IF EXISTS DATAMODEL_DATATABLES;
CREATE TABLE DATAMODEL_DATATABLES
(
    TABLENAME        VARCHAR(129) NOT NULL,
    TABLEINFORMATION VARCHAR(450),
    STATUS_ID        VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_DATE     VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER     VARCHAR(20) DEFAULT 'Platform',
    DATADOMAIN       VARCHAR(49),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS DATAMODEL_DOMAINS;
CREATE TABLE DATAMODEL_DOMAINS
(
    DOMAINNAME        VARCHAR(49) NOT NULL,
    DOMAININFORMATION VARCHAR(149),
    STATUS_ID         VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_DATE      VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER      VARCHAR(20) DEFAULT 'Platform',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

DROP TABLE IF EXISTS DATAMODEL_QUERIES;
CREATE TABLE IF NOT EXISTS DATAMODEL_QUERIES
(
    DATAMODEL_QUERIES_ID BIGSERIAL,
    DATAMODEL_TABLE      VARCHAR(64),
    DATAMODEL_DOMAIN     VARCHAR(64),
    DATAMODEL_QUERY_TXT  TEXT,
    DATAMODEL_QUERY_DTL  VARCHAR(499),
    MAINTAINED_DATE     TIMESTAMP   DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID           VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER        VARCHAR(20) DEFAULT 'Platform',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID)
);

-- DATA TIER
DROP TABLE IF EXISTS DATATIER_CRAWLERS;
CREATE TABLE DATATIER_CRAWLERS
(
    DATACRAWLER_ID      INTEGER PRIMARY KEY AUTOINCREMENT,
    TOKEN               VARCHAR(256),
    CRAWLEDTEXT_DETAILS TEXT,
    MAINTAINED_DATE        VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER        VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID           VARCHAR(10) DEFAULT 'Active',
    REGISTEREDAPP_GUID  VARCHAR(38),
    ORGANIZATION_GUID   VARCHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

DROP TABLE IF EXISTS DATATIER_SDP_DATAATTRIBUTES;
CREATE TABLE DATATIER_SDP_DATAATTRIBUTES
(
    DATATIER_SDP_DATAATTRIBUTE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DATAATTRIBUTE_ID   VARCHAR(38),
    DATAGENTYPE_ID     VARCHAR(38),
    PARAM_VALUE        VARCHAR(99),
    PARAM_VALUE_METADATA VARCHAR(159),
    MAINTAINED_DATE    TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    STATUS_ID          VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER       VARCHAR(20) DEFAULT 'Platform',
    REGISTEREDAPP_GUID VARCHAR(38),
    ORGANIZATION_GUID VARCHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (DATAATTRIBUTE_ID) REFERENCES REFDATA_DATAATTRIBUTES (DATAATTRIBUTE_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

DROP TABLE IF EXISTS DATATIER_SDP_DATASTRUCTURES;
CREATE TABLE DATATIER_SDP_DATASTRUCTURES
(
    DATASTRUCTURE_CORE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DATASTRUCTURE_NAME    VARCHAR(99),
    DATASTRUCTURE_DETAILS TEXT,
    MAINTAINED_DATE          VARCHAR(20)        DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    MAINTAINED_USER          VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID             VARCHAR(10) DEFAULT 'Active',
    REGISTEREDAPP_GUID    VARCHAR(38),
    ORGANIZATION_GUID   VARCHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

DROP TABLE IF EXISTS DATATIER_TOKENS;
CREATE TABLE DATATIER_TOKENS
(
    DATATOKEN_ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    TOKEN              VARCHAR(128),
    MAINTAINED_DATE       VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID          VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER       VARCHAR(20) DEFAULT 'Platform',
    REGISTEREDAPP_GUID VARCHAR(38),
    ORGANIZATION_GUID  VARCHAR(38),
    INTFC_TYPE         VARCHAR(10) DEFAULT 'API',
    DATASOURCE_ID      VARCHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID),
    FOREIGN KEY (DATASOURCE_ID) REFERENCES PLATFORM_DATASOURCES (PLATFORM_DATASOURCES_ID)
);

-- PLATFORM
DROP TABLE IF EXISTS PLATFORM_CODESETS;
CREATE TABLE PLATFORM_CODESETS
(
    PLATFORM_CODESET_ID VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    APPLICATION_GUID    VARCHAR(38),
    ORGANIZATION_GUID   VARCHAR(38),
    CODESETS_ID         VARCHAR(38),
    MAINTAINED_DATE        VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID           VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER        VARCHAR(20) DEFAULT 'Platform',
    ORIGINALCODE_VALUE  VARCHAR(40),
    ORIGINALCODE_DESC   VARCHAR(149),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (APPLICATION_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

CREATE TRIGGER PLATFORM_CODESETS_UUID_FORMATTER
AFTER INSERT ON PLATFORM_CODESETS
BEGIN
    UPDATE PLATFORM_CODESETS SET PLATFORM_CODESET_ID = concat(substr(PLATFORM_CODESET_ID,0,9)||'-'
    || substr(PLATFORM_CODESET_ID,9,4)||'-'|| substr(PLATFORM_CODESET_ID,13,4)||'-'
    || substr(PLATFORM_CODESET_ID,17,4)||'-'|| substr(PLATFORM_CODESET_ID,21,12))
    WHERE PLATFORM_CODESET_ID NOT LIKE '%-%';;
END;

DROP TABLE IF EXISTS PLATFORM_CODESETS_INDUSTRYSTDS;
CREATE TABLE PLATFORM_CODESETS_INDUSTRYSTDS
(
    TERMCODESET_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CUI            VARCHAR(8) NULL,
    LAT            VARCHAR(3) NULL,
    TS             VARCHAR(1) NULL,
    LUI            VARCHAR(10) NULL,
    STT            VARCHAR(3) NULL,
    SUI            VARCHAR(10) NULL,
    ISPREF         VARCHAR(1) NULL,
    AUI            VARCHAR(9) NULL,
    SAUI           VARCHAR(50) NULL,
    SCUI           VARCHAR(50) NULL,
    SDUI           VARCHAR(50) NULL,
    SAB            VARCHAR(25) NULL,
    TTY            VARCHAR(20) NULL,
    CODE           VARCHAR(50) NULL,
    STR            TEXT NULL,
    SRL            INT NULL,
    SUPPRESS       VARCHAR(1) NULL,
    CVF            INT NULL,
    MAINTAINED_DATE  VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE  VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    MAINTAINED_USER  VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID        VARCHAR(10) DEFAULT 'Active',
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (SAB) REFERENCES REFDATA_INDUSTRYSTDS (INDUSTRY_STD)
);

DROP TABLE IF EXISTS PLATFORM_CODESETS_XMAPS;
CREATE TABLE PLATFORM_CODESETS_XMAPS
(
    CODESETCROSSMAP_ID  VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    REGISTEREDAPP_GUID  VARCHAR(38),
    ORGANIZATION_GUID   VARCHAR(38),
    TERMINOLOGYSTD_FROM VARCHAR(25),
    TERMINOLOGYSTD_TO   VARCHAR(25),
    MAINTAINED_DATE        VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    STATUS_ID           VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER        VARCHAR(20) DEFAULT 'Platform',
    TRANSFORMCODE_VALUE VARCHAR(40),
    TRANSFORMCODE_DESC  VARCHAR(129),
    ORIGINALCODE_VALUE  VARCHAR(40),
    ORIGINALCODE_DESC   VARCHAR(129),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID),
    FOREIGN KEY (TERMINOLOGYSTD_FROM) REFERENCES REFDATA_TERMINOLOGYSTDS (TERMINOLOGY_STD),
    FOREIGN KEY (TERMINOLOGYSTD_TO) REFERENCES REFDATA_TERMINOLOGYSTDS (TERMINOLOGY_STD)
);

CREATE TRIGGER PLATFORM_CODESETS_XMAPS_UUID_FORMATTER
AFTER INSERT ON PLATFORM_CODESETS_XMAPS
BEGIN
    UPDATE REFDATA_INDUSTRIES_BUSINESS SET CODESETCROSSMAP_ID = concat(substr(CODESETCROSSMAP_ID,0,9)||'-'
    || substr(CODESETCROSSMAP_ID,9,4)||'-'|| substr(CODESETCROSSMAP_ID,13,4)||'-'
    || substr(CODESETCROSSMAP_ID,17,4)||'-'|| substr(CODESETCROSSMAP_ID,21,12))
    WHERE CODESETCROSSMAP_ID NOT LIKE '%-%';;
END;

DROP TABLE IF EXISTS PLATFORM_DATASOURCES;
CREATE TABLE PLATFORM_DATASOURCES
(
    PLATFORM_DATASOURCES_ID VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    DATASOURCE_NAME         VARCHAR(79),
    DATASOURCE_TYPE         VARCHAR(30),
    DATASOURCE_TECHNOLOGY   VARCHAR(40),
    HOST_NAME               VARCHAR(99),
    HOST_PORT               INT,
    HOST_UID                VARCHAR(79),
    HOST_ADDTNLDTLS          VARCHAR(149),
    CUSTOM_URL         VARCHAR(129),
    APP_TOKEN          VARCHAR(256),
    CUSTOM_TOKEN       VARCHAR(256),
    BEARER_TOKEN       VARCHAR(256),
    MAINTAINED_DATE            VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    STATUS_ID               VARCHAR(10)  DEFAULT 'Active',
    MAINTAINED_USER            VARCHAR(20)  DEFAULT 'Platform',
    ORGANIZATION_GUID       VARCHAR(38),
    REGISTEREDAPP_GUID      VARCHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

CREATE TRIGGER PLATFORM_DATASOURCES_UUID_FORMATTER
AFTER INSERT ON PLATFORM_DATASOURCES
BEGIN
    UPDATE PLATFORM_DATASOURCES SET PLATFORM_DATASOURCES_ID = concat(substr(PLATFORM_DATASOURCES_ID,0,9)||'-'
    || substr(PLATFORM_DATASOURCES_ID,9,4)||'-'|| substr(PLATFORM_DATASOURCES_ID,13,4)||'-'
    || substr(PLATFORM_DATASOURCES_ID,17,4)||'-'|| substr(PLATFORM_DATASOURCES_ID,21,12))
    WHERE PLATFORM_DATASOURCES_ID NOT LIKE '%-%';;
END;

DROP TABLE IF EXISTS PLATFORM_DATAGENERATION_DATAATTRIBUTES;
CREATE TABLE PLATFORM_DATAGENERATION_DATAATTRIBUTES
(
    DATAGENTYPE_ID          VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    DATAGENTYPE_DESCRIPTION VARCHAR(65),
    DEFINITION              VARCHAR(255),
    DEFINITION_METADATA  VARCHAR(75),
    DATAATTRIBUTE_ID        VARCHAR(38),
    MAINTAINED_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    STATUS_ID               VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER            VARCHAR(20) DEFAULT 'Platform',
    QUANTITY                INTEGER,
    MAXRECORDS_IN_SOURCE    INTEGER,
    REGISTEREDAPP_GUID      VARCHAR(38),
    ORGANIZATION_GUID       VARCHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID),
    FOREIGN KEY (DATAATTRIBUTE_ID) REFERENCES REFDATA_DATAATTRIBUTES (DATAATTRIBUTE_ID)
);

CREATE TRIGGER PLATFORM_DATAGENERATION_DATAATTRIBUTES_UUID_FORMATTER
AFTER INSERT ON PLATFORM_DATAGENERATION_DATAATTRIBUTES
BEGIN
    UPDATE PLATFORM_DATAGENERATION_DATAATTRIBUTES SET DATAGENTYPE_ID = concat(substr(DATAGENTYPE_ID,0,9)||'-'
    || substr(DATAGENTYPE_ID,9,4)||'-'|| substr(DATAGENTYPE_ID,13,4)||'-'
    || substr(DATAGENTYPE_ID,17,4)||'-'|| substr(DATAGENTYPE_ID,21,12))
    WHERE DATAGENTYPE_ID NOT LIKE '%-%';;
END;

DROP TABLE IF EXISTS PLATFORM_DATABUILDING_DATAATTRIBUTES;
CREATE TABLE PLATFORM_DATABUILDING_DATAATTRIBUTES
(
    DATABUILD_DATAATTRIBUTE_ID VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    DATABUILD_DESCRIPTION      VARCHAR(65),
    DEFINITION                 VARCHAR(255),
    MAINTAINED_DATE               VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    STATUS_ID                  VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER               VARCHAR(20) DEFAULT 'Platform',
    QUANTITY                   INTEGER,
    MAXRECORDS_IN_SOURCE       INTEGER,
    REGISTEREDAPP_GUID         VARCHAR(38),
    ORGANIZATION_GUID          VARCHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

CREATE TRIGGER PLATFORM_DATABUILDING_DATAATTRIBUTES_UUID_FORMATTER
AFTER INSERT ON PLATFORM_DATABUILDING_DATAATTRIBUTES
BEGIN
    UPDATE PLATFORM_DATABUILDING_DATAATTRIBUTES SET DATABUILD_DATAATTRIBUTE_ID = concat(substr(DATABUILD_DATAATTRIBUTE_ID,0,9)||'-'
    || substr(DATABUILD_DATAATTRIBUTE_ID,9,4)||'-'|| substr(DATABUILD_DATAATTRIBUTE_ID,13,4)||'-'
    || substr(DATABUILD_DATAATTRIBUTE_ID,17,4)||'-'|| substr(DATABUILD_DATAATTRIBUTE_ID,21,12))
    WHERE DATABUILD_DATAATTRIBUTE_ID NOT LIKE '%-%';;
END;

DROP TABLE IF EXISTS PLATFORM_DATABUILDING_DATAATTRIBUTES_DTL;
CREATE TABLE PLATFORM_DATABUILDING_DATAATTRIBUTES_DTL
(
    DATABUILD_DATAATTRIBUTE_DTL_ID VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    DATABUILD_DATAATTRIBUTE_ID     VARCHAR(38),
    DATAATTRIBUTE_ID               VARCHAR(38),
    MAINTAINED_DATE                VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    PARAM_NAME                     VARCHAR(30),
    PARAM_OPERATOR                 VARCHAR(7),
    PARAM_VALUE                    VARCHAR(65),
    STATUS_ID                      VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER                   VARCHAR(20) DEFAULT 'Platform',
    FOREIGN KEY (DATABUILD_DATAATTRIBUTE_ID) REFERENCES PLATFORM_DATABUILDING_DATAATTRIBUTES (DATABUILD_DATAATTRIBUTE_ID),
    FOREIGN KEY (PARAM_OPERATOR) REFERENCES REFDATA_OPERATIONTYPES (OPERATIONTYPE_ID),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (DATAATTRIBUTE_ID) REFERENCES REFDATA_DATAATTRIBUTES (DATAATTRIBUTE_ID)
);

CREATE TRIGGER PLATFORM_DATABUILDING_DATAATTRIBUTES_DTL_UUID_FORMATTER
AFTER INSERT ON PLATFORM_DATABUILDING_DATAATTRIBUTES_DTL
BEGIN
    UPDATE PLATFORM_DATABUILDING_DATAATTRIBUTES_DTL SET DATABUILD_DATAATTRIBUTE_DTL_ID = concat(substr(DATABUILD_DATAATTRIBUTE_DTL_ID,0,9)||'-'
    || substr(DATABUILD_DATAATTRIBUTE_DTL_ID,9,4)||'-'|| substr(DATABUILD_DATAATTRIBUTE_DTL_ID,13,4)||'-'
    || substr(DATABUILD_DATAATTRIBUTE_DTL_ID,17,4)||'-'|| substr(DATABUILD_DATAATTRIBUTE_DTL_ID,21,12))
    WHERE DATABUILD_DATAATTRIBUTE_DTL_ID NOT LIKE '%-%';;
END;

DROP TABLE IF EXISTS PLATFORM_DATABUILDING_DATASTRUCTURES;
CREATE TABLE PLATFORM_DATABUILDING_DATASTRUCTURES
(
    DATABUILD_DATASTRUCTURES_ID VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    DATABUILD_DESCRIPTION       VARCHAR(65),
    DEFINITION                  VARCHAR(255),
    DATASTRUCTURE_ID            VARCHAR(38),
    MAINTAINED_DATE                VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    STATUS_ID                   VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER                VARCHAR(20) DEFAULT 'Platform',
    QUANTITY                    INTEGER,
    MAXRECORDS_IN_SOURCE        INTEGER,
    REGISTEREDAPP_GUID          VARCHAR(38),
    ORGANIZATION_GUID           VARCHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (DATASTRUCTURE_ID) REFERENCES REFDATA_DATASTRUCTURES (DATASTRUCTURE_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

CREATE TRIGGER PLATFORM_DATABUILDING_DATASTRUCTURES_UUID_FORMATTER
AFTER INSERT ON PLATFORM_DATABUILDING_DATASTRUCTURES
BEGIN
    UPDATE PLATFORM_DATABUILDING_DATASTRUCTURES SET DATABUILD_DATASTRUCTURES_ID = concat(substr(DATABUILD_DATASTRUCTURES_ID,0,9)||'-'
    || substr(DATABUILD_DATASTRUCTURES_ID,9,4)||'-'|| substr(DATABUILD_DATASTRUCTURES_ID,13,4)||'-'
    || substr(DATABUILD_DATASTRUCTURES_ID,17,4)||'-'|| substr(DATABUILD_DATASTRUCTURES_ID,21,12))
    WHERE DATABUILD_DATASTRUCTURES_ID NOT LIKE '%-%';;
END;

DROP TABLE IF EXISTS REFDATA_RULESETS;
DROP TABLE IF EXISTS PLATFORM_RULESETS;
CREATE TABLE PLATFORM_RULESETS
(
    RULE_ID         VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    RULE_NAME       VARCHAR(65),
    MAINTAINED_DATE    VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    MAINTAINED_USER    VARCHAR(20) DEFAULT 'Platform',
    STATUS_ID       VARCHAR(10) DEFAULT 'Active',
    REGISTEREDAPP_GUID            VARCHAR(38),
    ORGANIZATION_GUID             VARCHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

CREATE TRIGGER PLATFORM_RULESETS_UUID_FORMATTER
AFTER INSERT ON PLATFORM_RULESETS
BEGIN
    UPDATE PLATFORM_RULESETS SET RULE_ID = concat(substr(RULE_ID,0,9)||'-'
    || substr(RULE_ID,9,4)||'-'|| substr(RULE_ID,13,4)||'-'
    || substr(RULE_ID,17,4)||'-'|| substr(RULE_ID,21,12))
    WHERE RULE_ID NOT LIKE '%-%';;
END;

DROP TABLE IF EXISTS PLATFORM_RULESETS_DEFINITIONS;
DROP TABLE IF EXISTS PLATFORM_RULESETS_DTL;
CREATE TABLE PLATFORM_RULESETS_DTL
(
    RULESET_DEFINITIONS_ID   VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    RULESET_DEFINITIONS_NAME VARCHAR(65),
    RULESET_ID               VARCHAR(38),
    STEPORDER_ID             INTEGER,
    OPERATIONTYPE_ID         VARCHAR(10),
    RULESET_DEFVALUE         VARCHAR(20),
    STATUS_ID                VARCHAR(10)  DEFAULT 'Active',
    MAINTAINED_DATE             VARCHAR(20)  DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE          VARCHAR(20)  DEFAULT (DATETIME('NOW', '+1 years')),
    MAINTAINED_USER             VARCHAR(20)  DEFAULT 'Platform',
    TERM_DATE                VARCHAR(20),
    DATAATTRIBUTE_ID         VARCHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (DATAATTRIBUTE_ID) REFERENCES REFDATA_DATAATTRIBUTES (DATAATTRIBUTE_ID),
    FOREIGN KEY (OPERATIONTYPE_ID) REFERENCES REFDATA_OPERATIONTYPES (OPERATIONTYPE_ID),
    FOREIGN KEY (RULESET_ID) REFERENCES PLATFORM_RULESETS (RULE_ID)
);

CREATE TRIGGER PLATFORM_RULESETS_DTL_UUID_FORMATTER
AFTER INSERT ON PLATFORM_RULESETS_DTL
BEGIN
    UPDATE PLATFORM_RULESETS_DTL SET RULESET_DEFINITIONS_ID = concat(substr(RULESET_DEFINITIONS_ID,0,9)||'-'
    || substr(RULESET_DEFINITIONS_ID,9,4)||'-'|| substr(RULESET_DEFINITIONS_ID,13,4)||'-'
    || substr(RULESET_DEFINITIONS_ID,17,4)||'-'|| substr(RULESET_DEFINITIONS_ID,21,12))
    WHERE RULESET_DEFINITIONS_ID NOT LIKE '%-%';;
END;

DROP TABLE IF EXISTS PLATFORM_TOKENS_XMAPS;
CREATE TABLE PLATFORM_TOKENS_XMAPS
(
    PLATFORM_TOKENS_XMAP_ID VARCHAR(38) PRIMARY KEY DEFAULT (UPPER(HEX(RANDOMBLOB(16)))),
    DATASTRUCTURE_ID        VARCHAR(38),
    XMAP_DETAILS            VARCHAR(75),
    DATAATTRIBUTE_ID        VARCHAR(38),
    FIELDORDER_ID           INTEGER DEFAULT 1,
    MAINTAINED_DATE            VARCHAR(20) DEFAULT (DATETIME('NOW', 'LOCALTIME')),
    EXPIRATION_DATE         VARCHAR(20) DEFAULT (DATETIME('NOW', '+1 years')),
    STATUS_ID               VARCHAR(10) DEFAULT 'Active',
    MAINTAINED_USER            VARCHAR(20) DEFAULT 'Platform',
    REGISTEREDAPP_GUID      VARCHAR(38),
    ORGANIZATION_GUID       VARCHAR(38),
    FOREIGN KEY (STATUS_ID) REFERENCES REFDATA_STATUS (STATUS_ID),
    FOREIGN KEY (DATAATTRIBUTE_ID) REFERENCES REFDATA_DATAATTRIBUTES (DATAATTRIBUTE_ID),
    FOREIGN KEY (REGISTEREDAPP_GUID) REFERENCES REFDATA_APPLICATIONS (APP_GUID),
    FOREIGN KEY (ORGANIZATION_GUID) REFERENCES REFDATA_ORGANIZATIONS (ORGANIZATION_GUID)
);

CREATE TRIGGER PLATFORM_TOKENS_XMAPS_UUID_FORMATTER
AFTER INSERT ON PLATFORM_TOKENS_XMAPS
BEGIN
    UPDATE PLATFORM_TOKENS_XMAPS SET PLATFORM_TOKENS_XMAP_ID = concat(substr(PLATFORM_TOKENS_XMAP_ID,0,9)||'-'
    || substr(PLATFORM_TOKENS_XMAP_ID,9,4)||'-'|| substr(PLATFORM_TOKENS_XMAP_ID,13,4)||'-'
    || substr(PLATFORM_TOKENS_XMAP_ID,17,4)||'-'|| substr(PLATFORM_TOKENS_XMAP_ID,21,12))
    WHERE PLATFORM_TOKENS_XMAP_ID NOT LIKE '%-%';;
END;

-- INDEXES
DROP INDEX IF EXISTS DATATIER_SDP_DATAATTRIBUTES_UINDEX
CREATE INDEX DATATIER_SDP_DATAATTRIBUTES_UINDEX
    ON DATATIER_SDP_DATAATTRIBUTES (DATATIER_SDP_DATAATTRIBUTE_ID, PARAM_VALUE,PARAM_VALUE_METADATA, MAINTAINED_DATE,
                                    DATAATTRIBUTE_ID, STATUS_ID, MAINTAINED_USER, REGISTEREDAPP_GUID);

DROP INDEX IF EXISTS DATATIER_CRAWLER_INDX;
CREATE INDEX DATATIER_CRAWLER_INDX ON DATATIER_CRAWLERS
    ( DATACRAWLER_ID ASC, TOKEN ASC, MAINTAINED_DATE ASC, STATUS_ID ASC, REGISTEREDAPP_GUID ASC, ORGANIZATION_GUID ASC )

DROP INDEX IF EXISTS DATATIER_SDP_DATASTRUCTURES_INDX;
CREATE INDEX DATATIER_SDP_DATASTRUCTURES_INDEX ON DATATIER_SDP_DATASTRUCTURES
    ( DATASTRUCTURE_CORE_ID ASC, DATASTRUCTURE_NAME ASC, MAINTAINED_DATE ASC, STATUS_ID ASC, REGISTEREDAPP_GUID ASC );

DROP INDEX IF EXISTS DATATIER_TOKENS_INDX;
CREATE INDEX DATATIER_TOKENS_INDEX ON DATATIER_TOKENS
    ( DATATOKEN_ID ASC, TOKEN ASC, MAINTAINED_DATE ASC,
     STATUS_ID ASC, REGISTEREDAPP_GUID ASC, ORGANIZATION_GUID ASC,
     INTFC_TYPE ASC, DATASOURCE_ID ASC);

DROP INDEX IF EXISTS PLATFORM_CODESETS_INDUSTRYSTDS_INDX;
CREATE INDEX PLATFORM_CODESETS_INDUSTRYSTDS_INDX ON PLATFORM_CODESETS_INDUSTRYSTDS
    ( TERMCODESET_ID ASC, MAINTAINED_DATE ASC, STATUS_ID ASC, CUI ASC,
     LAT ASC, TS ASC, LUI ASC, STT ASC, SUI ASC, ISPREF ASC, AUI ASC,
     SAUI ASC, SCUI ASC, SDUI ASC, SAB ASC, TTY ASC, CODE ASC, STR ASC,
     SRL ASC, SUPPRESS ASC, CVF ASC);